### ISSUE TITLE
the new version 0.4.1 causes pyhive stuck

### ISSUE THREAD

**Issue by landchenxuan** [cloudera/thrift_sasl#24] opened 2020-03-13 11:06 UTC
when downgrade to v0.3.0 the problem is gone.

how to reproduce:
```
from pyhive import hive

conn = hive.Connection(host='YOUR_HOST', port=10000, auth='LDAP', username='xx', password='yy', database='default')

def exec(sql):
    cursor = raw_c.cursor()
    cursor.execute(sql)
    cursor.fetchall()

exec('YOUR_SQL')
```

stack trace:
```
Traceback (most recent call last):
  File "testdb.py", line 42, in <module>
    exec('YOUR_SQL')
  File "testdb.py", line 30, in raw_exec
    cursor.fetchall()
  File "/usr/local/lib/python3.6/site-packages/pyhive/common.py", line 136, in fetchall
    return list(iter(self.fetchone, None))
  File "/usr/local/lib/python3.6/site-packages/pyhive/common.py", line 105, in fetchone
    self._fetch_while(lambda: not self._data and self._state != self._STATE_FINISHED)
  File "/usr/local/lib/python3.6/site-packages/pyhive/common.py", line 45, in _fetch_while
    self._fetch_more()
  File "/usr/local/lib/python3.6/site-packages/pyhive/hive.py", line 386, in _fetch_more
    response = self._connection.client.FetchResults(req)
  File "/usr/local/lib/python3.6/site-packages/TCLIService/TCLIService.py", line 714, in FetchResults
    return self.recv_FetchResults()
  File "/usr/local/lib/python3.6/site-packages/TCLIService/TCLIService.py", line 733, in recv_FetchResults
    result.read(iprot)
  File "/usr/local/lib/python3.6/site-packages/TCLIService/TCLIService.py", line 3470, in read
    self.success.read(iprot)
  File "/usr/local/lib/python3.6/site-packages/TCLIService/ttypes.py", line 6583, in read
    self.results.read(iprot)
  File "/usr/local/lib/python3.6/site-packages/TCLIService/ttypes.py", line 2867, in read
    _elem115.read(iprot)
  File "/usr/local/lib/python3.6/site-packages/TCLIService/ttypes.py", line 2741, in read
    self.stringVal.read(iprot)
  File "/usr/local/lib/python3.6/site-packages/TCLIService/ttypes.py", line 2521, in read
    _elem95 = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
  File "/usr/local/lib64/python3.6/site-packages/thrift/protocol/TProtocol.py", line 185, in readString
    return binary_to_str(self.readBinary())
  File "/usr/local/lib64/python3.6/site-packages/thrift/protocol/TBinaryProtocol.py", line 234, in readBinary
    s = self.trans.readAll(size)
  File "/usr/local/lib64/python3.6/site-packages/thrift/transport/TTransport.py", line 62, in readAll
    chunk = self.read(sz - have)
  File "/usr/local/lib/python3.6/site-packages/thrift_sasl/__init__.py", line 173, in read
    self._read_frame()
  File "/usr/local/lib/python3.6/site-packages/thrift_sasl/__init__.py", line 177, in _read_frame
    header = self._trans.read(4)
  File "/usr/local/lib64/python3.6/site-packages/thrift/transport/TSocket.py", line 126, in read
    buff = self.handle.recv(sz)    # got stuck here
```

**Comment by timarmstrong** [comment] 2020-03-31 01:42
Looks like a duplicate of #22

**Closed as completed by timarmstrong** 2020-03-31 01:42 UTC
